### ISSUE TITLE
Make save/load themes visible in the UI

### ISSUE THREAD

**Issue by SantoRemedio** [UECIDE/UECIDE#125]
**Is your feature request related to a problem? Please describe.**
The option for importing/exporting themes is invisible and can only be discovered by accident. 

**Describe the solution you'd like**
Modify the *Preferences* dialog to make the option explicit. 

**Describe alternatives you've considered**
Two additional buttons in the bottom of the *Preferences* dialog will be enough.

**Additional context**
Here I renamed the actions as Save/Load (shorter than Import/Export).
![screenshot at 2019-01-21 07-47-07](https://user-images.githubusercontent.com/46725121/51470434-9ffa1000-1d52-11e9-9126-2acc7c3cb760.png)

I think there is a problem with using the "theme" word in three places, with slightly different meanings.

(Yeah, I'm bad at graphics).

**Comment by majenkotech** [comment]
I have been considering ways of making theme management better.  I would like to have it so that `.utheme` files can be placed (by the plugin manager maybe) into a `themes` folder and you can select which theme to use from a simple list / dropdown. Import / export (or load / save or whatever) would then just operate on those files. It would make distributing themes easier if they were in the plugin manager. 

The current menu entry for import / export is very much a stop-gap solution.

I'd also quite like to write a proper theme editor plugin sometime that gives you a live graphical display of your changes as you're making them. That's not going to be that easy though.

**Comment by majenkotech** [comment]
For now this does seem a reasonable compromise to make it a little more obvious how to import/export themes.  And simple to implement, so done!

Added in aa6b91b
