### ISSUE TITLE
Sketch name in Serial Terminal window bar

### ISSUE THREAD

**Issue by SantoRemedio** [UECIDE/UECIDE#141]
**Is your feature request related to a problem? Please describe.**
Currently the Serial Terminal put the device id (like /dev/ttyUSB1) in the title bar. When working with two or more boards, it's not easy to determinate to which board it's attached to what Serial Terminal window.

![Screenshot at 2019-03-20 08-26-21](https://user-images.githubusercontent.com/46725121/54681951-5f1d3e00-4aec-11e9-9df2-426c51100a42.png)

**Describe the solution you'd like**
Put the name of the sketch in the window title, like
![Screenshot at 2019-03-20 08-26-212](https://user-images.githubusercontent.com/46725121/54682137-dc48b300-4aec-11e9-9834-b770fe492fca.png)

**Describe alternatives you've considered**
Using an external terminal emulator to avoid confusion.

**Comment by majenkotech** [comment]
Not so sure about that one.  The terminal isn't really associated with the sketch. It's associated with the device that is selected in the current window. And if you open multiple windows (as is the future plan) on different ports from within the same sketch window the sketch name would be irrelevant, since you're not just looking at the one device.

Better may be to display the USB or associated board information in the titlebar so you can better see which device you are talking to.

**Comment by majenkotech** [comment]
Added in b19c11c
