### ISSUE TITLE
windows 10

### ISSUE THREAD

**Issue by jlbachiochi** [UECIDE/UECIDE#85]
Using UECIDE with Picadillo-35T (MAX32)

![uecide](https://cloud.githubusercontent.com/assets/8245351/13461237/3a719d50-e04e-11e5-8c57-77e105325542.jpg)

While there is no complaint about 'not finding' Picadillo.h,it can't seem to find the Picadillo class.  Wondering if it has somethng to do with where windows 10 is expecting to find things.

**Comment by majenkotech** [comment]
You have the wrong board selected. The Picadillo code only gets compiled if you have the picadillo board selected. That is because it contains register references that aren't common to all PIC32 chips (and certainly not AVR ATMega2560 which you have selected at the moment). Just select the Picadillo as your board and it should compile fine.

**Comment by jlbachiochi** [comment]
Yes, you are correct I selected both Picadillo-35t and Chipkit.  Unselecting the Chipkit button fixed my issue.  I look forward to working with UECIDE  --jeff
