### ISSUE TITLE
Can't register for forim access

### ISSUE THREAD

**Issue by vanepp** [UECIDE/UECIDE#90]
I tried to register as vanepp in the forums but the confirmation email never arrived. I just tried to reregister and it tells me the user name and email address are both in use. I clicked on the resend 
confirmation email button on the register page but still no confirmation email. I can't see a way in the
forums page to contact the administrator as it suggests so I'm trying here.

**Comment by majenkotech** [comment]
Your account has been activated. U do not know where the activation email has gone. It may have been diverted as spam somewhere along the line.

**Comment by vanepp** [comment]
Thanks, first time I've seen an activation email get lost and 
unfortunatly I'm retired and no longer have access to the sendmail logs to 
see if it was SFU's system that lost it.

Peter Van Epp

**Comment by majenkotech** [comment]
The fault is at my end - looking into it now.

**Comment by majenkotech** [comment]
Got it! That was fun. The email is relayed via Google's Gmail servers. Which I had all set up properly and working. Then suddenly it started connecting to the servers through an IPv6 address instead of the IPv4 address I had configured, so it was being rejected as coming from an unauthorized source.

So now it works. 

Still, it's helped keep the spammers at bay...
